### ISSUE TITLE
unity camera animation ...

### ISSUE THREAD

**Issue by davoodkharmanzar** [keijiro/NeuronAnimator#5]
thanks for this great tool :]

i want to animating an unity camera based on movements of neuron actor's head ...
is it possible and how to do that?

**Comment by keijiro** [comment]
Sorry but your question is not relevant to this repository. This issue tracker is dedicated to solve bugs/problems caused by/in NeuronAnimator. I recommend using Unity forum to get an answer to a general Unity question like this.
